# P.I.T.C.E.S. Framework Configuration
# Parallel Integrated Task Contexting Engine System v1.0
# Integration with JAEGIS v2.2 and N.L.D.S. Tier 0

# Framework Metadata
framework:
  name: "P.I.T.C.E.S."
  full_name: "Parallel Integrated Task Contexting Engine System"
  version: "1.0.0"
  description: "Hybrid workflow system with Sequential Waterfall and CI/AR modes"
  author: "JAEGIS Enhanced Agent System"
  license: "MIT"
  repository: "https://github.com/usemanusai/JAEGIS"

# Core Configuration
core:
  # Default workflow mode selection
  default_mode: "auto_select"  # auto_select, sequential_waterfall, ci_ar, hybrid
  
  # Intelligent mode selection thresholds
  mode_selection:
    complexity_thresholds:
      task_count:
        simple: 5
        moderate: 15
        complex: 50
        highly_complex: 999999
      dependency_ratio:
        simple: 0.2
        moderate: 0.4
        complex: 0.7
        highly_complex: 1.0
      resource_diversity:
        simple: 3
        moderate: 6
        complex: 12
        highly_complex: 999999
      estimated_duration_hours:
        simple: 8
        moderate: 40
        complex: 200
        highly_complex: 999999
    
    # Mode preference scoring
    mode_preferences:
      sequential_waterfall:
        best_for:
          - "well_defined_requirements"
          - "linear_dependencies"
          - "stable_scope"
          - "regulatory_compliance"
        complexity_preference:
          - "simple"
          - "moderate"
        resource_efficiency: 0.85
        predictability: 0.90
        risk_tolerance: "low"
      
      ci_ar:
        best_for:
          - "adaptive_requirements"
          - "parallel_execution"
          - "iterative_development"
          - "innovation_projects"
        complexity_preference:
          - "complex"
          - "highly_complex"
        resource_efficiency: 0.75
        adaptability: 0.95
        risk_tolerance: "high"
      
      hybrid:
        best_for:
          - "mixed_requirements"
          - "phased_delivery"
          - "balanced_approach"
        complexity_preference:
          - "moderate"
          - "complex"
        resource_efficiency: 0.80
        adaptability: 0.85
        risk_tolerance: "medium"

# Performance Configuration
performance:
  # Execution targets
  targets:
    completion_rate: 0.95
    resource_efficiency: 0.80
    average_task_duration_variance: 0.20
    jaegis_coordination_efficiency: 0.90
    
  # Timeout settings
  timeouts:
    task_execution_max_hours: 24
    workflow_execution_max_days: 30
    dependency_check_timeout_seconds: 30
    jaegis_command_timeout_seconds: 300
    
  # Retry configuration
  retry:
    max_task_retries: 3
    retry_delay_seconds: 60
    exponential_backoff: true
    retry_on_failures:
      - "network_error"
      - "temporary_resource_unavailable"
      - "jaegis_timeout"

# JAEGIS Integration
jaegis_integration:
  # Connection settings
  enabled: true
  interface_type: "enhanced"  # standard, enhanced
  coordination_mode: "adaptive"  # standard, adaptive, real_time
  
  # Command execution
  command_execution:
    parallel_limit: 10
    timeout_seconds: 300
    retry_failed_commands: true
    validate_command_syntax: true
    
  # Squad coordination
  squad_coordination:
    auto_select_squads: true
    load_balancing: true
    resource_monitoring: true
    performance_tracking: true
    
  # Supported JAEGIS commands
  supported_commands:
    orchestration:
      - "JAEGIS:ORCHESTRATE"
      - "JAEGIS:COORDINATE"
      - "JAEGIS:VALIDATE"
      - "JAEGIS:MONITOR"
    
    coordination:
      - "JOHN:PLAN"
      - "FRED:IMPLEMENT"
      - "TYLER:VALIDATE"
    
    specialized:
      - "ARCHITECT:DESIGN"
      - "TECHNICAL:LEAD"
      - "INTEGRATE:CONNECT"
      - "QA:TEST"
    
    squads:
      - "GARAS:DETECT"
      - "GARAS:ANALYZE"
      - "GARAS:RESOLVE"
      - "IUAS:MONITOR"
      - "IUAS:UPDATE"
      - "CHIMERA:OPTIMIZE"

# N.L.D.S. Integration
nlds_integration:
  # Connection settings
  enabled: true
  tier_level: 0
  processing_mode: "enhanced"  # basic, enhanced, full
  
  # Natural language processing
  nlp_processing:
    confidence_threshold: 0.85
    processing_dimensions:
      - "logical"
      - "emotional"
      - "creative"
    alternative_interpretations: true
    context_preservation: true
    
  # Task translation
  task_translation:
    auto_translate_descriptions: true
    generate_jaegis_commands: true
    validate_translations: true
    confidence_validation: true
    
  # User interaction
  user_interaction:
    natural_language_input: true
    conversational_interface: true
    context_aware_responses: true
    learning_adaptation: true

# Workflow Execution
execution:
  # Sequential Waterfall mode
  sequential_waterfall:
    strict_dependencies: true
    fail_fast: true
    checkpoint_validation: true
    rollback_on_failure: true
    progress_reporting_interval: "1h"
    
  # CI/AR mode (Continuous Integration / Adaptive Reasoning)
  ci_ar:
    parallel_execution_limit: 20
    adaptive_resource_allocation: true
    real_time_optimization: true
    failure_tolerance: 0.30
    learning_feedback_loop: true
    progress_reporting_interval: "30m"
    
  # Hybrid mode
  hybrid:
    sequential_task_threshold: 3  # Tasks with >3 dependencies go sequential
    complexity_split_threshold: "complex"
    dynamic_mode_switching: true
    optimization_intervals: "2h"
    
  # Common settings
  common:
    resource_monitoring: true
    performance_analytics: true
    audit_logging: true
    checkpoint_creation: true
    progress_notifications: true

# Resource Management
resources:
  # Resource types
  types:
    - "computational"
    - "storage"
    - "network"
    - "human"
    - "external_api"
    - "jaegis_agent"
    
  # Allocation strategies
  allocation:
    strategy: "dynamic"  # static, dynamic, adaptive
    load_balancing: true
    priority_based: true
    resource_pooling: true
    
  # Monitoring
  monitoring:
    utilization_tracking: true
    performance_metrics: true
    bottleneck_detection: true
    auto_scaling: true
    
  # Limits
  limits:
    max_concurrent_tasks: 50
    max_resource_utilization: 0.90
    max_memory_usage_gb: 16
    max_cpu_utilization: 0.85

# Monitoring and Analytics
monitoring:
  # Metrics collection
  metrics:
    enabled: true
    collection_interval_seconds: 60
    retention_days: 90
    
    # Collected metrics
    collect:
      - "task_execution_time"
      - "resource_utilization"
      - "workflow_completion_rate"
      - "error_rates"
      - "jaegis_coordination_efficiency"
      - "nlds_translation_accuracy"
      - "user_satisfaction_scores"
    
  # Alerting
  alerting:
    enabled: true
    channels:
      - "email"
      - "slack"
      - "webhook"
    
    # Alert conditions
    conditions:
      high_failure_rate:
        threshold: 0.20
        window_minutes: 30
      resource_exhaustion:
        threshold: 0.95
        window_minutes: 5
      workflow_timeout:
        threshold_hours: 48
      jaegis_coordination_failure:
        threshold: 0.10
        window_minutes: 15
  
  # Dashboard
  dashboard:
    enabled: true
    real_time_updates: true
    historical_data: true
    export_capabilities: true

# Security and Compliance
security:
  # Authentication
  authentication:
    required: true
    method: "jwt"  # jwt, api_key, oauth
    token_expiration_hours: 24
    
  # Authorization
  authorization:
    role_based: true
    permission_levels:
      - "read"
      - "execute"
      - "admin"
    
  # Audit logging
  audit:
    enabled: true
    log_all_actions: true
    retention_days: 365
    encryption: true
    
  # Data protection
  data_protection:
    encryption_at_rest: true
    encryption_in_transit: true
    pii_detection: true
    data_anonymization: true

# Development and Testing
development:
  # Debug settings
  debug:
    enabled: false
    log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
    detailed_tracing: false
    
  # Testing
  testing:
    unit_tests: true
    integration_tests: true
    performance_tests: true
    security_tests: true
    
    # Test environments
    environments:
      - "development"
      - "staging"
      - "production"
    
    # Test data
    test_data:
      synthetic_workflows: true
      load_testing: true
      chaos_engineering: false

# External Integrations
integrations:
  # GitHub
  github:
    enabled: true
    repository: "usemanusai/JAEGIS"
    sync_interval_minutes: 60
    auto_documentation: true
    
  # OpenRouter.ai
  openrouter:
    enabled: true
    api_keys_pool_size: 3000
    load_balancing: true
    rate_limiting: true
    
  # Database
  database:
    type: "postgresql"  # postgresql, mysql, mongodb
    connection_pool_size: 20
    query_timeout_seconds: 30
    
  # Cache
  cache:
    type: "redis"  # redis, memcached, in_memory
    ttl_seconds: 3600
    max_memory_mb: 1024
    
  # Message Queue
  message_queue:
    type: "rabbitmq"  # rabbitmq, kafka, redis
    queue_size_limit: 10000
    message_ttl_seconds: 86400

# Deployment Configuration
deployment:
  # Environment
  environment: "production"  # development, staging, production
  
  # Scaling
  scaling:
    auto_scaling: true
    min_instances: 2
    max_instances: 10
    cpu_threshold: 0.70
    memory_threshold: 0.80
    
  # Health checks
  health_checks:
    enabled: true
    interval_seconds: 30
    timeout_seconds: 10
    failure_threshold: 3
    
  # Backup and recovery
  backup:
    enabled: true
    interval_hours: 6
    retention_days: 30
    encryption: true
